server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NGanzyuk/JavaTasks.git
          searchPaths: SpringHW/HW1/ConfigRepository
          default-label: main